---
- name: Configure local host
  hosts: all

  vars_files:
      - default.config.yml

  tasks:
    - name: display machine architecture
      debug:
        msg: 
          - "{{ ansible_architecture }}"
          -  "{{ ansible_user_id }}"

    - name: set passwordless sudo for admin group
      copy:
        content: "{{ sudoers_custom_config }}"
        dest: /private/etc/sudoers.d/custom
        mode: 0440
        validate: 'visudo -cf %s'
      become: true

  roles:
    - homebrew
    - macvim



